version: "3.2"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: donhub
    depends_on:
      - db


  frontend:
    build: ./frontend
    ports:
      - "8081:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: donhub
     
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 
